# Generated by Django 5.1.2 on 2024-10-19 15:49

import core.functions.gen_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=core.functions.gen_functions.generate_random_string, max_length=10, unique=True),
        ),
    ]
