# Generated by Django 5.1.2 on 2024-10-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_interestcategory_alter_userimage_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
