# Generated by Django 5.1.2 on 2024-10-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_interest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.interestcategory'),
        ),
    ]
