# Generated by Django 5.1.2 on 2024-10-19 23:03

import core.functions.gen_functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_like_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=core.functions.gen_functions.get_today)),
                ('received_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user', to=settings.AUTH_USER_MODEL)),
                ('sent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
