# Generated by Django 5.1.2 on 2024-10-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestcategory',
            options={'verbose_name': 'Interest category', 'verbose_name_plural': 'Interest categories'},
        ),
        migrations.AddField(
            model_name='like',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
