# Generated by Django 5.1.2 on 2024-10-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_interestcategory_options_like_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='profs', verbose_name='Profile Image'),
        ),
    ]
