# Generated by Django 5.1.2 on 2024-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='top_interests',
            field=models.TextField(blank=True),
        ),
    ]
