# Generated by Django 5.1.2 on 2024-10-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_stat_top_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
